---
title: "Data Import"
output: github_document
---


This document will show how to import data


```{r}
library(tidyverse)
library(readxl)
library(haven)
```

## Import the FAS litters csv


```{r}
litters_df = read_csv("/Users/wangmingyin/Desktop/data science 1/data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## Look at the dataset

```{r}
litters_df

head(litters_df)
tail(litters_df, 10)
```

```{r eval=FALSE}
view(litters_df)
```

# #learning assessment import FAS pups
```{r}
pups_df = janitor::clean_names(pups_df)
pups_df = read_csv("data/FAS_pups.csv")


```

use absolute path
```{r}
pups_df = read_csv("/Users/wangmingyin/Desktop/data science 1/data_import_examples/FAS_pups.csv")

```

## Look at read_csv options 
```{r}
litters_df=
  read_csv(
    file = "/Users/wangmingyin/Desktop/data science 1/data_import_examples/FAS_litters.csv",
   na = c(".", "NA", ""),
   col_types = cols(
     Group = col_factor()
   )
  
   )

```

## Import an excel file

Import MLB 2011 summart data

```{r}
mlb_df= read_excel("/Users/wangmingyin/Desktop/data science 1/data_import_examples/mlb11.xlsx", sheet = "mlb11")
```


## Import SAS data
```{r}
pulse_df=read_sas("/Users/wangmingyin/Desktop/data science 1/data_import_examples/public_pulse_data.sas7bdat")
```



## Never use read.csv()


Never do this either:

```{r}
litters_df$L
```