---
title: "Data Import"
output: github_document
---


This document will show how to import data


```{r}
library(tidyverse)
library(readxl)
library(haven)
```

This document will show how to manipulate data

```{r}
litters_df = read_csv("/Users/wangmingyin/Desktop/data science 1/data_import_examples/FAS_litters.csv", na = c(".", "NA", ""))
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("/Users/wangmingyin/Desktop/data science 1/data_import_examples/FAS_pups.csv",na = c(".", "NA", ""))
pups_df = janitor::clean_names(pups_df)

```

## `select`

```{r}
select(litters_df, group, litter_number, gd0_weight)
```


```{r}
select(litters_df, group, gd18_weight)
```

```{r}
select(litters_df, -pups_survive)
```

```{r}
select(litters_df, -(group:gd18_weight))
```

```{r}
select(litters_df, starts_with("gd"))

select(litters_df, contains("pups"))


```
```{r}
select(litters_df, GROUP=group)

rename(litters_df, GROUP=group)

select(litters_df, litter_numebr, gd0_weight, everything())

relocate(litters_df, litter_number,gd0_weight )
```

